### ISSUE TITLE
Inquiry about Full Pre-trained Model Release

### ISSUE THREAD

**Issue by moonboy12138** [zhu-xlab/DOFA#11]
I noticed that the pre-trained models only include the encoder weights. Will the complete pre-trained model be released?

**Comment by ShadowXZT** [comment]
Sure, we will release them soon after a business trip.

**Comment by ShadowXZT** [comment]
The full pretrained weights have been uploaded to [huggingface](https://huggingface.co/XShadow/DOFA). Please kindly check it out.
