### ISSUE TITLE
Data preprocessing for downstream tasks

### ISSUE THREAD

**Issue by antofuller** [zhu-xlab/DOFA#13]
Hello, great work with DOFA!

I'd like to use DOFA on some Sentinel-2 downstream tasks, like m-eurosat, and want to make sure I get the data preprocessing right. In this file: `https://github.com/zhu-xlab/DOFA/blob/master/pretraining/datasets/ofall_dataset.py`, I see you have Sentinel-2 mean and std values listed that are used to normalize data. However, these seem like statistics of values that are already normalized between 0 and 255 (presumably so the images can be stored as 8-bit integers). Since m-eurosat contains unnormalized reflectance values, it seems like I'd need to first normalize between 0 and 255, then use your mean and std values to normalize again. If so, how was the first normalization achieved, i.e., that maps from raw values to values between 0 and 255?

My apologies if this code is somewhere else in the repo that I have missed. 

Thank you!
Anthony

**Comment by zhitong-xiong** [comment]
Hello Anthony,

Thank you for your interest in our work.

For Sentinel-2 images, we use normalized data from the Satlas dataset. The preprocessing steps [https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images](https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images) are as follows:

> Sentinel-2 Images:

> 3-band models: We input the TCI (True Color Image) file provided with the scene, which is an 8-bit image normalized by ESA to the 0-255 range. For model input, this image is normalized by dividing the 0-255 RGB values by 255, retaining the RGB order.

> Multi-band models: These models input 9 channels. The non-TCI channels are normalized from the 16-bit source data by dividing by 8160 and clipping to the 0-1 range. The channels are ordered as follows:

> TCI (3 channels: RGB, divided by 255)
> B05, B06, B07, B08, B11, B12 (divided by 8160, clipped to 0-1)
> You can see this order specified in the configuration files, such as configs/satlas_explorer_solar_farm.txt. For more context, here’s an example of downloading Sentinel-2 images, normalizing the bands, and saving them as .npy files, which can be used in multi-image, multi-band Satlas models.

Let me know if you have any further questions!
