### ISSUE TITLE
Code for BigEarthNet downstream task

### ISSUE THREAD

**Issue by PlekhanovaElena** [zhu-xlab/DOFA#17]
Hi DOFA team,

Great work!

I was wondering how to reproduce your result on the BigEarthNet dataset?
Do you by any chance have code for it or for the dataloader?

I found the [dofa_base_resisc45.py](https://github.com/zhu-xlab/DOFA/blob/master/downstream_tasks/classification/configs/dofa_base_resisc45.py), but it seem to have a specific RGB data_preprocessor, and I'm not sure how to replace it for BigEarthNet with Sentinel2 data.

Elena

**Comment by xiong-zhitong** [comment]
Hi sorry for the late response. Here [GeoFM](https://github.com/xiong-zhitong/GeoFM) we provide the code for more downstream datasets on GeoBench.
