### ISSUE TITLE
add  fine-tuning examples for dense prediction tasks including regression and semantic segmentation tasks

### ISSUE THREAD

**Issue by ShadowXZT** [zhu-xlab/DOFA#2]
Integrate DOFA backbone with methods like [ViT-CoMer](https://arxiv.org/pdf/2403.07392.pdf) for dense prediction tasks,
 including regression and semantic segmentation tasks

**Comment by andrewaf1** [comment]
Hi! I found this paper and code really interesting and have begun using it via torchgeo.

I'm very curious how this method would work with ViT-CoMer. My understanding of that method is that it employs a ViT branch, a convolutional feature pyramid branch, and a module to fuse the resulting features. For DOFA, would a separate convolutional branch for each satellite source be required? I would also be very interested in seeing some examples of semantic segmentation, particularly how the features are transformed into a feature pyramid for UPerNet.

**Comment by ShadowXZT** [comment]
Thanks for your interest. We have added example of using DOFA for the image classification task.
We are working on adding the semantic segmentation examples. 
Please stay tuned!

**Comment by ShadowXZT** [comment]
An example of using DOFA for segmentation tasks is added. We use DOFA as the backbone and UperNet as the segmentation head.
