### ISSUE TITLE
utils import issue - which library versions are used? 

### ISSUE THREAD

**Issue by alimkarimi** [zhu-xlab/DOFA#3]
Hi there. Very cool work! 

Can you please post the versions of the libraries that are listed in the requirements.txt file? I am running into an issue with using the demo.ipynb as I get an issue loading the vit base model in the cell below "Load the pre-trained weights of DOFA base model" (in the import statement "from models_dwv import vit_base_patch16")

Specifically the error is "ModuleNotFoundError: No module named 'util'". I have kornia, numpy, rasterio, timm, and torch all in my environment. I am wondering if it may be an issue with which version of timm I am on, as timm is the only library in that list that has a built in function for sin/cos based 2d positional embeddings (as far as I am aware).

This is the full error message:
<img width="635" alt="Screenshot 2024-04-01 at 10 12 44 PM" src="https://github.com/zhu-xlab/DOFA/assets/32401390/b2bb4646-b05e-4a71-86bb-b8a1de11010d">

**Comment by alimkarimi** [comment]
Is it possibly from the MAE library? https://github.com/facebookresearch/mae/blob/main/util/pos_embed.py . The pos_embed.py file here has a function called "get_1d_sincos_pos_embed_from_grid".

**Comment by ShadowXZT** [comment]
Hi @alimkarimi , we updated the repo and the problem should be fixed now. 
The demo file has also been updated. Thanks for your interest.

**Comment by alimkarimi** [comment]
Thanks! I am able to run inference now for the demo notebook examples.
