### ISSUE TITLE
pretraining code?

### ISSUE THREAD

**Issue by robmarkcole** [zhu-xlab/DOFA#8]
I see the code for fine tuning, but cannot see it for pretraining..?

**Comment by ShadowXZT** [comment]
Thanks for your interests. We will upload the pre-training code by the middle of this month.

**Comment by ShadowXZT** [comment]
Pretraining code added. We will provide detailed instructions and documentation very soon.

**Comment by Vipermdl** [comment]
nice job. where is the pretrain weights

**Comment by xiong-zhitong** [comment]
> nice job. where is the pretrain weights

https://huggingface.co/XShadow/DOFA
